server:
  port: 8899
spring:
  datasource:
    username: anteater
    password: Hasdw__01
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.242:3306/hyy?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出.
    default-statement-timeout: 3
  #  配置查找mapper.xml文件
  mapper-locations: "classpath:/mapper/*.xml"
  global-config:
    db-config:
      #      配置主键id自增
      id-type: auto
      logic-delete-value: 1 #逻辑已删除值（默认为1）
      logic-not-delete-value: 0 #逻辑已删除值（默认为0）